apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-asd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-asd
  template:
    metadata:
      labels:
        app: springboot-asd
    spec:
      containers:
        - name: springboot-asd
          image: dranzzer/cc-demo:cc-demo
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-asd
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: springboot-asd
